using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Web;
using System.Text;

namespace WcfStarService
{
    [ServiceContract]
    public interface IServiceMvcHolcim
    {
        [OperationContract]
        string[] ws_stars_create_distributor(string account_name,
             string account_owner,
             string sap_account_number,
             string sap_account_status,
             string account_type,
             string account_subtype,
             string primary_sold_to,
             string sap_term_of_payment,
             string sap_credit_limit,
             string sap_remaining_credit,
             string address_1,
             string address_2,
             string address_3,
             string country,
             string region,
             string city,
             string postal_code,
             string latitude,
             string email,
             string phone,
             string extension_1,
             string fax,
             string mobile_1,
             string sap_created_by,
             DateTime sap_created_Date,
             string sap_last_modified_by,
             DateTime sap_last_modified_date,
             string account_site,
             string account_source,
             string annual_revenue,
             string billing_address,
             string created_by,
             string data_com_key,
             string description,
             string employees,
             string industry,
             string last_modified_by,
             string ownership,
             string rating,
             string shipping_address,
             string sic_code,
             string sic_description,
             string ticker_symbol,
             string website,
             string active,
             string customer_priority,
             string number_of_location,
             string sla,
             DateTime sla_expiration_date,
             string sla_serial_number,
             string tranportation,
             string upsell_opportunity);

        [OperationContract]
        string[] ws_stars_update_distributor(string distributorID,
             string account_name,
             string account_owner,
             string sap_account_number,
             string sap_account_status,
             string account_type,
             string account_subtype,
             string primary_sold_to,
             string sap_term_of_payment,
             string sap_credit_limit,
             string sap_remaining_credit,
             string address_1,
             string address_2,
             string address_3,
             string country,
             string region,
             string city,
             string postal_code,
             string latitude,
             string email,
             string phone,
             string extension_1,
             string fax,
             string mobile_1,
             string sap_created_by,
             DateTime sap_created_Date,
             string sap_last_modified_by,
             DateTime sap_last_modified_date,
             string account_site,
             string account_source,
             string annual_revenue,
             string billing_address,
             string created_by,
             string data_com_key,
             string description,
             string employees,
             string industry,
             string last_modified_by,
             string ownership,
             string rating,
             string shipping_address,
             string sic_code,
             string sic_description,
             string ticker_symbol,
             string website,
             string active,
             string customer_priority,
             string number_of_location,
             string sla,
             DateTime sla_expiration_date,
             string sla_serial_number,
             string tranportation,
             string upsell_opportunity);


        [OperationContract]
        string[] ws_stars_create_retailer(string account_name,
            string account_owner,
            string stars_prospect_id,
            string sap_account_number,
            string sap_account_status,
            string account_type,
            string account_subtype,
            string primary_sold_to,
            string address_1,
            string address_2,
            string address_3,
            string country,
            string region,
            string city,
            string postal_code,
            string latitude,
            string email,
            string extension_1,
            string fax,
            string mobile_1,
            string phone,
            long sap_created_by,
            DateTime sap_created_date,
            string sap_last_modified_by,
            DateTime sap_last_modified_date);

        [OperationContract]
        string[] ws_stars_update_retailer(
            string retailerId,
            string account_name,
            string account_owner,
            string stars_prospect_id,
            string sap_account_number,
            string sap_account_status,
            string account_type,
            string account_subtype,
            string primary_sold_to,
            string address_1,
            string address_2,
            string address_3,
            string country,
            string region,
            string city,
            string postal_code,
            string latitude,
            string email,
            string extension_1,
            string fax,
            string mobile_1,
            string phone,
            long sap_created_by,
            DateTime sap_created_date,
            string sap_last_modified_by,
            DateTime sap_last_modified_date);

        [OperationContract]
        string[] ws_stars_create_prospect(string account_name,
            string account_owner,
            string stars_prospect_id,
            string sap_account_number,
            string sap_account_status,
            string account_type,
            string account_subtype,
            string primary_sold_to,
            string address_1,
            string address_2,
            string address_3,
            string country,
            string region,
            string city,
            string postal_code,
            string latitude,
            string email,
            string extension_1,
            string fax,
            string mobile_1,
            string phone,
            long sap_created_by,
            DateTime sap_created_date,
            string sap_last_modified_by,
            DateTime sap_last_modified_date);

        [OperationContract]
        string[] ws_stars_update_prospect(
            string propectId,
            string account_name,
            string account_owner,
            string stars_prospect_id,
            string sap_account_number,
            string sap_account_status,
            string account_type,
            string account_subtype,
            string primary_sold_to,
            string address_1,
            string address_2,
            string address_3,
            string country,
            string region,
            string city,
            string postal_code,
            string latitude,
            string email,
            string extension_1,
            string fax,
            string mobile_1,
            string phone,
            long sap_created_by,
            DateTime sap_created_date,
            string sap_last_modified_by,
            DateTime sap_last_modified_date);

        [OperationContract]
        string[] ws_stars_create_contact(
            string sap_contact_number,
            string name,
            string title,
            DateTime birthdate,
            string sex,
            string marital_status,
            string account_name,
            string phone,
            string phone_2,
            string mobile,
            string fax,
            string extension,
            string email,
            string sap_created_by,
            DateTime sap_created_date,
            string sap_last_modified_by,
            DateTime sap_last_modified_date);

        [OperationContract]
        string[] ws_stars_update_contact(
            string contactId,
            string sap_contact_number,
            string name,
            string title,
            DateTime birthdate,
            string sex,
            string marital_status,
            string account_name,
            string phone,
            string phone_2,
            string mobile,
            string fax,
            string extension,
            string email,
            string sap_created_by,
            DateTime sap_created_date,
            string sap_last_modified_by,
            DateTime sap_last_modified_date);

        [OperationContract]
        string[] ws_stars_create_salesarea(string sales_organization,
            string segmen_code,
            string segmen_description,
            string distribution_channel,
            string division,
            string sales_district,
            string customer_group,
            string sales_group,
            string account_group,
            string sales_office,
            string region,
            string deletion);

        [OperationContract]
        string[] ws_create_contact_relation(string sap_number_contact,
            string decision_maker,
            string relation_category,
            string rev_contact_number,
            string created_by,
            string last_modify_by,
            string source_system);

        [OperationContract]
        string[] ws_update_contact_relation(string contactToContactId,
            string sap_number_contact,
            string decision_maker,
            string relation_category,
            string rev_contact_number,
            string created_by,
            string last_modify_by,
            string source_system);

        [OperationContract]
        string[] ws_create_warehouse(string holcim_warehouse_id,
            string holcim_warehouse_name,
            string primary_sold_to,
            string address_1,
            string address_2,
            string address_3,
            string country,
            string region,
            string city,
            string postal_code);

        [OperationContract]
        string[] ws_update_warehouse(string warehouseId,
            string holcim_warehouse_id,
            string holcim_warehouse_name,
            string primary_sold_to,
            string address_1,
            string address_2,
            string address_3,
            string country,
            string region,
            string city,
            string postal_code);

        [OperationContract]
        IList<TypeActivity> getServiceAllTypeActivity();        
    }
}
