//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceEntities13 : DbContext
    {
        public ServiceEntities13()
            : base("name=ServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Activitylog> Activitylogs { get; set; }
        public DbSet<ContactRelation> ContactRelations { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Distributor> Distributors { get; set; }
        public DbSet<Retailer> Retailers { get; set; }
        public DbSet<Salesarea> Salesareas { get; set; }
        public DbSet<TypeActivity> TypeActivities { get; set; }
        public DbSet<warehouse> warehouses { get; set; }
    }
}
